CREATE TABLE AIRLINE(
	CODE INT CONSTRAINT PK_AIRLINE PRIMARY KEY NOT NULL,
	NAME VARCHAR(256) CONSTRAINT UK_AIRLINE UNIQUE NOT NULL,
	COUNTRY VARCHAR(64)
);

CREATE TABLE AIRPORT(
	CODE INT CONSTRAINT PK_AIRPORT PRIMARY KEY NOT NULL,
	NAME VARCHAR(256) NOT NULL,
	COUNTRY VARCHAR(64),
	CITY VARCHAR(100),
	CONSTRAINT UK_AIRPORT UNIQUE(NAME, COUNTRY)
);

CREATE TABLE AIRPLANE(
	CODE INT CONSTRAINT PK_AIRPLANE PRIMARY KEY NOT NULL,
	TYPE CHAR(20) NOT NULL,
	SEATS INT CHECK(SEATS > 0),
	YEAR INT
);

CREATE TABLE FLIGHT(
	FNUMBER INT CONSTRAINT PK_FLIGHT PRIMARY KEY NOT NULL,
	AIRLINE_OPERATOR INT REFERENCES AIRLINE(CODE),
	DEP_AIRPORT INT REFERENCES AIRPORT(CODE),
	ARR_AIRPORT INT REFERENCES AIRPORT(CODE),
	FLIGHT_TIME TIME,
	FLIGHT_DURATION TIME,
	AIRPLANE INT REFERENCES AIRPLANE(CODE)
);

CREATE TABLE CUSTOMER(
	ID INT CONSTRAINT PK_CUSTOMER PRIMARY KEY NOT NULL,
	FNAME VARCHAR(20) NOT NULL,
	LNAME VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(50) CONSTRAINT UK_CUSTOMER UNIQUE CHECK(EMAIL LIKE '%@%.%' AND LEN(EMAIL) >= 6)
);

CREATE TABLE AGENCY(
	NAME VARCHAR(50) CONSTRAINT PK_AGENCY PRIMARY KEY NOT NULL,
	COUNTRY VARCHAR(64),
	CITY VARCHAR(100),
	PHONE VARCHAR(16) CONSTRAINT UK_AGENCY UNIQUE NOT NULL
);

CREATE TABLE BOOKING(
	CODE INT CONSTRAINT PK_BOOKING PRIMARY KEY NOT NULL,
	AGENCY VARCHAR(50) REFERENCES AGENCY(NAME),
	AIRLINE_CODE INT REFERENCES AIRLINE(CODE),
	FLIGHT_NUMBER INT REFERENCES FLIGHT(FNUMBER),
	CUSTOMER_ID INT REFERENCES CUSTOMER(ID),
	BOOKING_DATE DATE,
	FLIGHT_DATE DATE CHECK(FLIGHT_DATE >= BOOKING_DATE),
	PRICE INT,
	STATUS INT NOT NULL DEFAULT 0 CHECK(STATUS = 1 OR STATUS = 0)
);
